### ISSUE TITLE
It would be better to have weeklies pushed to subscriber's email.

### ISSUE THREAD

**Issue by guanqun** [pingcap/weekly#5]
Setup a subscriber list and send out the weekly via email.

**Comment by shenli** [comment]
@guanqun Good idea! I will set up the email newsletter.
Thanks!

**Comment by guanqun** [comment]
Keep me posted. :)

**Comment by shenli** [comment]
@guanqun We build a newsletter. There will be a test newsletter at this weekend. 
You can subscribe it here: http://eepurl.com/bT1FAv
